# Generated by Django 5.1.4 on 2025-01-01 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0002_alter_question_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
        migrations.AlterField(
            model_name='answer',
            name='survey_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qna.surveysubmission'),
        ),
    ]
