# Generated by Django 5.1.4 on 2025-01-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0003_remove_question_slug_alter_answer_survey_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
