# Generated by Django 5.1.4 on 2025-01-30 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qna', '0004_alter_patient_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='survey_submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='qna.surveysubmission'),
        ),
    ]
